# workflows/gene_network/Snakefile

configfile: "../../config.yaml"

SEEDS        = config['seeds']       # {name: fasta_path}
DBS          = config['dbs']         # {name: blast_db_string}
RESULTS_DIR  = config['results_network_dir']

'''
1. 
2. Construct graph from gene IDs
3. Output (pickle object of Graph) can be visualized via Cytoscape (through Jupyter Notebook)
'''

